// <auto-generated />
using System;
using Common.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106165939_OnlyDbAppSettings2")]
    partial class OnlyDbAppSettings2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Common.Types.AppSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AppClosingTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("AppStartTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Cooldown")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastNotification")
                        .HasColumnType("TEXT");

                    b.Property<string>("MongoConnectionString")
                        .HasColumnType("TEXT");

                    b.Property<float>("PriceRange")
                        .HasColumnType("REAL");

                    b.Property<string>("TelegramBotToken")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TrackerGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Common.Types.StockTracking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("RegularMarketPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrackingToBuy")
                        .HasColumnType("INTEGER");

                    b.Property<float>("TriggerPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("StockTrackings");
                });
#pragma warning restore 612, 618
        }
    }
}
